In [ ]:
from Forms import *

table15 = FormTable(13, CLASSICAL_TRUTH, [CLASSICAL_IMPLICATION, CLASSICAL_NEGATION])

def test():
    count = 0
    for expression in table15.__iter__():
        count += 1
        #if count % 10000 == 0:
        #    print(count)
    print(count)

%prun test()

In [ ]:
def func():
    i = iter("ABCDE")
    return [next(i) if c=="_" else c for c in "C_CC_CNN___"]
%timeit func()

In [ ]:
def func():
    i = iter([1,2,3,4,5])
    return [next(i) if c==0 else c for c in [-1, 0, -1, -1, 0, -1, -2, -2, 0, 0, 0]]
%timeit func()

In [ ]:
import numpy as np
a1 = np.repeat(np.array([-1, 0, -1, -1, 0, -1, -2, -2, 0, 0, 0]), 1000)
a2 = np.repeat(np.array([1,2,3,4,5]), 1000)
def func():
    a3 = a1.copy()
    a3[a1==0] = a2
    return a3
%timeit func()

In [ ]:
from Forms import *

arr = Form([FormOpSpec(CLASSICAL_IMPLICATION, 4), FormOpSpec(CLASSICAL_NEGATION, 2)], [FormConstSpec("o", 2)])
b = Form([FormOpSpec(CLASSICAL_IMPLICATION, 4), FormOpSpec(CLASSICAL_NEGATION, 2)])
print(arr.base_element)
print(arr._order_grounded(0))
print(arr._order_grounded(-1))
print(arr._order_grounded(-2))
print(arr._order_grounded(-3))
print("===========================")
element = np.array([-3, -3, 0, -1, -2, -3, -2, 0, -3, -1, 0])
print(element)
print(arr.isa_member(element))
print("===========================")
print("===========================")
print("===========================")
arr._ground_element(element, -3)
print(element)
print("===========================")
element = np.array([-3, -3, 0, -1, -2, -3, -2, 0, -3, -1, 0])
print(element)
arr._reset_right(element, -1, 5)
print(element)
print("===========================")
arr._next(element, -1)
arr._next(element, -1)
print(element)
print("===========================")
element = np.array([-3, -3, -3, -3, -2, -1, -2, 0, -1, 0, 0])
arr._reset_right(element, -2, 7)
print(element)

In [ ]:
count = 0
for exp in arr.raw_all:
    count += 1
print(count)
count = 0
for exp in arr.__iter__():
    count += 1
print(count)

In [ ]:
arr.check_array()

In [ ]:
from ModelTools import *
CN_STANDARD_MODEL(np.array([-3, -2, 1, -2, 2, 1], dtype=np.int8), "Verify")
#i(i(i(i(i(X,Y),i(n(Z),n(U))),Z),V),i(i(V,X),i(U,X)))
CN_STANDARD_MODEL(np.array([-3, -2, -2, -2, -2, -2, 1, 2, -2, -1, 3, -1, 4, 3, 5, -2, -2, 5, 1, -2, 4, 1], dtype=np.int8), "Verify")

In [ ]:
%load_ext line_profiler

from Forms import *
arr = Form([FormOpSpec(CLASSICAL_IMPLICATION, 6), FormOpSpec(CLASSICAL_NEGATION, 7)])

#%lprun -m Forms print(a.array.shape)
print(arr.length)
print(arr.array.shape)

In [ ]:
#C6N7: 9m 39.1s
#20: 95.3
#18: 22.1
#16: 4.5
#14: .9

In [1]:
%load_ext line_profiler
%load_ext memory_profiler

from TreeForms import *
from TestingUtils import *

def func():
    arr = np.ones(3, dtype=np.int8)

    CN = TreeForm(CN_OPERATIONS[1:], CN_OPERATIONS[0], 11)
    test_table = ModelTable(CN_SPEC, counter_model_folder="tmp_testing")

    CN.process_tree(11, test_table, BLANK_VAMPIRE_WRAPPER, "reamining_testing.txt")

func()
#%memit func()
#%prun func()
#%lprun -f TreeForm.Node.process func()
#%lprun -f TreeForm.Node.calculate func()
#%lprun -f apply_fill_to_cache func()
#%lprun -f Model.calculate func()
#%lprun -f dimensionally_reorganized_array func()
#%lprun -m ModelTools func()
#%lprun -m FillTools func()

Processed 2146 formulas.


In [ ]:
#10: .7s old
#11: 1.3s old
#12: 3.6s old
#13: 26.1s
#14: 60.0s
#15: 292s

#Mems:
#10: 
#14: 169.81 MiB
#15: 310.27 MiB

In [1]:
import numpy as np
import FillTools

FillTools._initialize_fill_table(3)

print(FillTools._fill_table_fills.shape)

print(FillTools._fill_table_fills)

print(FillTools.fill_dimensions(FillTools.Fill(1, 2)))

print(FillTools.fill_upward_cleave(1, 3))

print(FillTools.fill_result_disassembly(np.array([[True, True], [False, True]])))

(3, 5)
[[0 0 0 0 0]
 [0 0 1 1 1]
 [0 1 0 1 2]]
[0, 1]
[False False  True  True  True]
[ True False]


In [ ]:
i = 0
''.join(["abcdef"[(i := i + 1)] if c == "_" else c for c in "1_2_3_"])

In [4]:
import numpy as np

np.vstack((np.random.rand(3,3,3) > .5).nonzero()).shape

(3, 15)

In [8]:
import numpy as np
import random

A: list[int] = [random.randrange(0, 10, 1) for _ in range(10)]
B: list[int] = [random.randrange(0, 10, 1) for _ in range(10)]
Arr = np.array(A, dtype=np.int8)
Brr = np.array(B, dtype=np.int8)
Asp: list[np.int8] = [np.int8(a) for a in A]
Bsp: list[np.int8] = [np.int8(b) for b in B]

In [ ]:
%timeit [a for a in A if a not in B]

In [ ]:
%timeit [a for a in Asp if a not in Bsp]

In [ ]:
%timeit np.array([a for a in Arr if a not in Brr], dtype=np.int8)

In [ ]:
%timeit np.setdiff1d(Arr, Brr, assume_unique=True).astype(np.int8)

In [ ]:
%timeit [a for a in Arr.tolist() if a not in Brr.tolist()]

In [ ]:
print(CN._PSUDEO_NODE_CACHE[2])

In [ ]:
import numpy as np
from ModelTools import dimensionally_reorganized_array

target = np.array([5, 2, 1, 0, 3], dtype=np.int8)
current = np.array([3, 1], dtype=np.int8)
arr = np.arange(9).reshape(3,3).astype(np.int8)
reorganized = dimensionally_reorganized_array(target, arr, current)
print(reorganized.shape)
print(arr[:,:])
print(reorganized[:,:,:,:,:])
print(arr[:,0])
print(reorganized[:,:,0,:,:])
print(arr[:,1])
print(reorganized[:,:,1,:,:])
print(arr[:,2])
print(reorganized[:,:,2,:,:])
print(arr[0,:])
print(reorganized[:,:,:,:,0])
print(arr[1,:])
print(reorganized[:,:,:,:,1])
print(arr[2,:])
print(reorganized[:,:,:,:,2])

CN__
C_N_
NC__
NNN_

In [ ]:
from MathUtilities import bells
from FillTools import FillTable.Fills, _check_surjective_table, _generate_surjective_table_dumb, _generate_surjective_table_pseudo
import numpy as np

num = 6
print(bells(num))
fills, table = FillTable._initialize_fill_table(num)
print(fills.shape)
print(table.shape)
#print(fills[fills.max(axis=1)==2])
print(fills)

In [ ]:
_generate_surjective_table_dumb(num, fills)

In [ ]:
_generate_surjective_table_pseudo(num, fills)

In [ ]:
_check_surjective_table(num, fills)

In [ ]:
%load_ext line_profiler
from Forms import *
from VampireUtils import *

def func():
    test_forms = FormTable(12, CLASSICAL_TRUTH, [CLASSICAL_IMPLICATION, CLASSICAL_NEGATION]) #14
    test_models = ModelTable(CN_SPEC, CN_STANDARD_MODEL) #[CLASSICAL_TRUTH, CLASSICAL_IMPLICATION, CLASSICAL_NEGATION]
    #test_models = ModelTable(Model([np.array([True, False, True], dtype=np.bool_), 
    #                                np.array([[1, 2, 0], [2, 2, 0], [1, 0, 1]], dtype=np.int8),
    #                                np.array([1, 2, 1], dtype=np.int8)])) #random 3 size
    
    #for forms, fills in test_forms.array:
    #    print(forms)

    test_forms.process(test_models, BLANK_VAMPIRE_WRAPPER, "test_excess.txt")

#%lprun -m ModelTools func()
%lprun -m Forms func()

In [ ]:
#11: 4s
#12: 13s
#13: 39s
#14: 118s

In [ ]:
list(range(1, 10))[1::2]

In [ ]:
def remove_duplicates(lst):
    seen = set()
    return [x for x in lst if x not in seen and not seen.add(x)]

# Example usage
lst = [1, 2, 2, 6, 3, 4, 1, 5, 3]
result = remove_duplicates(lst)
print(result)  # Output: [1, 2, 3, 4, 5]

In [ ]:
import numpy as np

arr = np.arange(8).reshape(2,2,2)
diagonal_dims = [2, 1, 0]
#print(arr.diagonal(0, diagonal_dims[0], diagonal_dims[1]))
#for indices in np.ndindex(arr.shape):
#    if indices[diagonal_dims[0]]==indices[diagonal_dims[1]]:
#        print(arr[indices])

grids = np.stack(np.meshgrid(*[np.arange(dim) for dim in arr.shape], indexing='ij'))
mask = np.all(grids[diagonal_dims[0]]==grids[diagonal_dims], axis=0)
print(arr[mask])
mask

In [ ]:
import numpy as np
from ModelTools import apply_fill_to_cache, _apply_fill_to_cache_forced_iteration

A = np.arange(81).reshape(3,3,3,3)
print(apply_fill_to_cache(A, np.array([5,5,5,2,3,3])))
print(_apply_fill_to_cache_forced_iteration(A, np.array([5,5,5,2,3,3])))
print(A)

In [ ]:
import numpy as np
def func(x):
    x += 1

A = np.array([0, 1, 2])
func(A[1:])
A

In [ ]:
def valid_dyck_word(word, arity = 2):
    if word[0]!=0:
        return False
    
    for i in range(1, len(word)):
        if word[i] > i * (arity - 1):
            return False
        if word[i] < word[i-1]:
            return False
        
    if word[-1]!=(len(word)-1)*(arity - 1):
        return False
        
    return True

def _iterate_word(word, arity = 2):
    word[-1] += 1
    i = len(word) - 1
    while word[i] > (i + 1) * (arity - 1):
        if i==0:
            word[0] = 10 * arity
            return
        word[i-1] += 1
        word[i] = word[i-1]
    
def word_iter(count, arity = 2):
    current_word = [0] * (count-1)
    while valid_dyck_word([0]+current_word+[count * (arity - 1)], arity=arity):
        yield [0]+current_word+[count * (arity - 1)]
        _iterate_word(current_word, arity=arity)

def dyck_word_to_exp(word, letter="D"):
    exp = ""
    for i in range(1, len(word)):
        exp += letter + "_" * (word[i] - word[i-1])
    exp += "_"
    return exp

word = [0,1,1,3,4]
print(valid_dyck_word(word))
print(dyck_word_to_exp(word))

word = [0,1,2,5,8]
print(valid_dyck_word(word, arity=3))
print(dyck_word_to_exp(word))
word = [1,2,6]
_iterate_word(word, arity=3)
print(word)

In [ ]:
for word in word_iter(3, arity=3):
    print(dyck_word_to_exp(word))

In [ ]:



CN = Form([('C', 2, 4), ('N', 1, 2)])
print("================")
print(CN.ground_state)
print("================")
print(CN._valid_state("C_CC_C__NN_"))
print("================")
print(CN._valid_state("CCCC_____NN"))
print("================")
print(CN._valid_state("CCC____C___"))
print("================")
print(CN._ground_state("C_CC_CNN___", level=2))

In [ ]:
CND = Form([('C', 2, 2), ('N', 1, 1), ('D', 3, 2)])
CND.check_iter()
for exp in CND:
    print(exp)

In [ ]:
CN.check_iter()

In [ ]:
for exp in CN:
    print(exp)

In [ ]:
'CCC_NC__N__'

In [ ]:
A = [0, 1, 2, 3]
A[2]

In [ ]:
ses = [set([1,2,3]), set([4,5,6]), set([2,4,6])]
list(set(itertools.chain.from_iterable(ses)))

In [ ]:
from FillTools import Fill


L5 = Fill(5)
for x in L5:
    print(x)
L5.check_iter()

In [ ]:
ord('a')-ord('b')

In [ ]:
from ModelTools import Model

expression = "TCCabNa"
a_mod = Model(operation_tables={"T": np.array([True, False]), "C": np.array([[0, 0], [0, 1]]), "N": np.array([1, 0])}, size=2)
print(a_mod.compile_expression(expression))
#a_mod.check_tautological(expression, "Unlikely")
a_mod.__call__(expression, "Verify")

In [ ]:
import numpy as np

A = np.random.rand(1, 1, 3, 1)
B = np.random.rand(1, 4, 1, 1)
(A * B).shape
C = np.random.rand(5, 2)
def idxC(*args):
    return C[*args]
idxC(np.array([2, 3]), np.array([[0], [1]]))
np.take(A, [0], axis=1).shape

In [ ]:
[0, 1, 2, 3][1:-1]

In [ ]:
hasattr([], "__len__")