In [ ]:
from Forms import *

table15 = FormTable(13, CLASSICAL_TRUTH, [CLASSICAL_IMPLICATION, CLASSICAL_NEGATION])

def test():
    count = 0
    for expression in table15.__iter__():
        count += 1
        #if count % 10000 == 0:
        #    print(count)
    print(count)

%prun test()

In [ ]:
def func():
    i = iter("ABCDE")
    return [next(i) if c=="_" else c for c in "C_CC_CNN___"]
%timeit func()

In [ ]:
def func():
    i = iter([1,2,3,4,5])
    return [next(i) if c==0 else c for c in [-1, 0, -1, -1, 0, -1, -2, -2, 0, 0, 0]]
%timeit func()

In [ ]:
import numpy as np
a1 = np.repeat(np.array([-1, 0, -1, -1, 0, -1, -2, -2, 0, 0, 0]), 1000)
a2 = np.repeat(np.array([1,2,3,4,5]), 1000)
def func():
    a3 = a1.copy()
    a3[a1==0] = a2
    return a3
%timeit func()

In [ ]:
from Forms import *

arr = Form([FormOpSpec(CLASSICAL_IMPLICATION, 4), FormOpSpec(CLASSICAL_NEGATION, 2)], [FormConstSpec("o", 2)])
b = Form([FormOpSpec(CLASSICAL_IMPLICATION, 4), FormOpSpec(CLASSICAL_NEGATION, 2)])
print(arr.base_element)
print(arr._order_grounded(0))
print(arr._order_grounded(-1))
print(arr._order_grounded(-2))
print(arr._order_grounded(-3))
print("===========================")
element = np.array([-3, -3, 0, -1, -2, -3, -2, 0, -3, -1, 0])
print(element)
print(arr.isa_member(element))
print("===========================")
print("===========================")
print("===========================")
arr._ground_element(element, -3)
print(element)
print("===========================")
element = np.array([-3, -3, 0, -1, -2, -3, -2, 0, -3, -1, 0])
print(element)
arr._reset_right(element, -1, 5)
print(element)
print("===========================")
arr._next(element, -1)
arr._next(element, -1)
print(element)
print("===========================")
element = np.array([-3, -3, -3, -3, -2, -1, -2, 0, -1, 0, 0])
arr._reset_right(element, -2, 7)
print(element)

In [ ]:
count = 0
for exp in arr.raw_all:
    count += 1
print(count)
count = 0
for exp in arr.__iter__():
    count += 1
print(count)

In [ ]:
arr.check_array()

In [ ]:
from ModelTools import *
CN_STANDARD_MODEL(np.array([-3, -2, 1, -2, 2, 1], dtype=np.int8), "Verify")
#i(i(i(i(i(X,Y),i(n(Z),n(U))),Z),V),i(i(V,X),i(U,X)))
CN_STANDARD_MODEL(np.array([-3, -2, -2, -2, -2, -2, 1, 2, -2, -1, 3, -1, 4, 3, 5, -2, -2, 5, 1, -2, 4, 1], dtype=np.int8), "Verify")

In [ ]:
%load_ext line_profiler

from Forms import *
arr = Form([FormOpSpec(CLASSICAL_IMPLICATION, 6), FormOpSpec(CLASSICAL_NEGATION, 7)])

#%lprun -m Forms print(a.array.shape)
print(arr.length)
print(arr.array.shape)

In [ ]:
#C6N7: 9m 39.1s
#20: 95.3
#18: 22.1
#16: 4.5
#14: .9

In [1]:
#%load_ext line_profiler
#%load_ext memory_profiler

from TreeForms import *
from TestingUtils import *

def func():
    vampire_executable_file_name: str = "../.././vampire"
    counter_model_sets: list[list[str]] = [["t(i(i(i(i(i(X,Y),i(n(Z),n(U))),Z),V),i(i(V,X),i(U,X))))"]]
    counter_model_folder: str = "CNCounterModels"

    CN = TreeForm(CN_OPERATIONS[1:], CN_OPERATIONS[0], 14)
    test_table = ModelTable(CN_SPEC, counter_model_folder=counter_model_folder)

    num = 14

    vampire_wrapper = create_vampire_countermodel_instance(vampire_executable_file_name, counter_model_sets, counter_model_folder, CN_SPEC, verify_models=True)

    CN.process_tree(num, test_table, vampire_wrapper, "test_pass.txt")

func()
#%memit func()
#%prun func()
#%lprun -f TreeForm.Node.process func()
#%lprun -f TreeForm.Node.calculate func()
#%lprun -f apply_fill_to_cache func()
#%lprun -f Model.calculate func()
#%lprun -f dimensionally_reorganized_array func()
#%lprun -m ModelTools func()
#%lprun -m FillTools func()

CNCounterModels/countermodel-2-0
Recovered 1 models.
Processed 5797 formulas.


In [2]:
#Times:
#@13 cache
#10: 1.3s
#11: 1.6s
#12: 3.4s
#13: 9.7s
#14: 38.5s
#15: 

#Memory:
#@13 cache
#13: 124.62MiB
#14: 125.10 MiB
#@14 cache
#14: 169.97 MiB

In [1]:
%load_ext line_profiler
%load_ext memory_profiler

from TreeForms import *
from TestingUtils import *

def func():
    arr = np.ones(2, dtype=np.int8)

    C0 = TreeForm(C_OPERATIONS[1:], C_OPERATIONS[0], 13)
    test_table = ModelTable(C0_SPEC, counter_model_folder="tmp_testing")

    C0.process_tree(13, test_table, BLANK_VAMPIRE_WRAPPER, "reamining_testing.txt")

func()

Processed 132 formulas.


In [1]:
import numpy as np
import FillTools

FillTools._initialize_fill_table(3)

print(FillTools._fill_table_fills.shape)

print(FillTools._fill_table_fills)

print(FillTools.fill_dimensions(FillTools.Fill(1, 2)))

print(FillTools.fill_upward_cleave(1, 3))

print(FillTools.fill_result_disassembly_application(np.array([[True, True], [False, True]])))

(3, 5)
[[0 0 0 0 0]
 [0 0 1 1 1]
 [0 1 0 1 2]]
[0, 1]
[False False  True  True  True]
[ True False]


In [ ]:
i = 0
''.join(["abcdef"[(i := i + 1)] if c == "_" else c for c in "1_2_3_"])

In [5]:
import itertools
s = 4
d = 2
list(itertools.product(range(2), repeat=4))
list(itertools.product(range(1), repeat=4))

[(0, 0, 0, 0)]

In [2]:
import itertools

list(itertools.product([1,2,3], [4,5]))

[(1, 4), (1, 5), (2, 4), (2, 5), (3, 4), (3, 5)]

In [6]:
import numpy as np

np.sum([np.array([1,2]), np.array([1,2])], axis=0)

array([2, 4])

In [1]:
from MathUtilities import *

for i in range(5):
    print(degenerate_constant_combinations(i))

print("=========")
for i in range(5):
    print(nondegenerate_constant_combinations(i))

1
2
5
15
52
0
0
2
9
36


In [2]:
import numpy as np

tuple(np.array([1,2,3]))

(1, 2, 3)

In [1]:
from FillTools import *
from FillTools import _initialize_fill_table

%prun _initialize_fill_table(9)

         3576009 function calls (3570677 primitive calls) in 7.933 seconds

   Ordered by: internal time

   ncalls  tottime  percall  cumtime  percall filename:lineno(function)
        1    2.544    2.544    7.123    7.123 FillTools.py:292(_generate_subsumptive_table)
    21147    2.248    0.000    2.435    0.000 FillTools.py:269(_subsumed_points)
   109832    1.186    0.000    1.893    0.000 FillTools.py:238(point_to_fill)
        2    0.485    0.243    0.485    0.243 {method 'astype' of 'numpy.ndarray' objects}
        1    0.447    0.447    7.933    7.933 FillTools.py:354(_initialize_fill_table)
    21146    0.191    0.000    0.252    0.000 FillTools.py:194(_point_to_fill_cached)
   958024    0.165    0.000    0.165    0.000 {method 'keys' of 'dict' objects}
  1309816    0.146    0.000    0.146    0.000 {method 'append' of 'list' objects}
   109832    0.108    0.000    0.108    0.000 {built-in method __new__ of type object at 0x00007FF9ABA9A4B0}
    21147    0.096    0.000    0.096

In [46]:
import functools
from MathUtilities import bells


eval_fill((0, 1, 0, 0, 1))

4: 0, 0
3: 1, 1
2: 0, 2
1: 0, 2
0: 1, 2


15

=================================Initialized Process Tracker
N/A
[--------------------] 0.0% : 0/111


Thinking
N/A
[--------------------] 0.0% : 0/111
Thinking
a^2 + b^2 = c^2 + AI
[--------------------] 0.0% : 0/111
Thinking
a^2 + b^2 = c^2 + AI
[#########-----------] 0.45% : 50/111
Trolling
a^2 + b^2 = c^2 + AI
[#########-----------] 0.45% : 50/111
Trolling
a^2 + b^2 = c^2 + AI
[####----------------] 0.225% : 25/111
Trolling
a^2 + b^2 = c^2 + AI
[#########-----------] 0.495% : 55/111
Trolling
a^2 + b^2 = c^2 + AI
[###############-----] 0.766% : 85/111


In [33]:
B(1, 3)

3

In [1]:
from ModelTools import *

mod = Model(C0_SPEC, model_filename="C0CCC12C3CC40OCC031.out")
print(mod.operation_definitions)
print(mod.constant_definitions)


{OperationSpec(symbol='T', vampire_symbol='t', arity=1, default_table=array([False,  True])): array([False, False, False,  True, False,  True, False]), OperationSpec(symbol='C', vampire_symbol='i', arity=2, default_table=array([[1, 1],
       [0, 1]], dtype=int8)): array([[6, 6, 4, 4, 6, 4, 6],
       [6, 6, 6, 4, 6, 4, 6],
       [6, 4, 4, 4, 6, 4, 6],
       [7, 3, 2, 4, 5, 4, 7],
       [5, 6, 5, 4, 6, 4, 5],
       [3, 3, 3, 4, 5, 4, 3],
       [6, 6, 6, 4, 4, 4, 6]], dtype=int8)}
{ConstantSpec(symbol='F', vampire_symbol='o', default_value=0): 0}


In [8]:
import numpy as np
import random

A: list[int] = [random.randrange(0, 10, 1) for _ in range(10)]
B: list[int] = [random.randrange(0, 10, 1) for _ in range(10)]
Arr = np.array(A, dtype=np.int8)
Brr = np.array(B, dtype=np.int8)
Asp: list[np.int8] = [np.int8(a) for a in A]
Bsp: list[np.int8] = [np.int8(b) for b in B]

In [ ]:
%timeit [a for a in A if a not in B]

In [ ]:
%timeit [a for a in Asp if a not in Bsp]

In [ ]:
%timeit np.array([a for a in Arr if a not in Brr], dtype=np.int8)

In [ ]:
%timeit np.setdiff1d(Arr, Brr, assume_unique=True).astype(np.int8)

In [ ]:
%timeit [a for a in Arr.tolist() if a not in Brr.tolist()]

In [ ]:
print(CN._PSUDEO_NODE_CACHE[2])

In [8]:
def node_size_combos(remaining_slots: int, remaining_size: int) -> Iterable[tuple[int, ...]]:
    if remaining_slots==1:
        yield (remaining_size, )
    else:
        for i in range(1, remaining_size + 1 - remaining_slots + 1):
            for comb in node_size_combos(remaining_slots - 1, remaining_size - i):
                yield (i,) + comb

list(node_size_combos(3, 6))

[(1, 1, 4),
 (1, 2, 3),
 (1, 3, 2),
 (1, 4, 1),
 (2, 1, 3),
 (2, 2, 2),
 (2, 3, 1),
 (3, 1, 2),
 (3, 2, 1),
 (4, 1, 1)]

CN__
C_N_
NC__
NNN_

In [ ]:
from MathUtilities import bells
from FillTools import FillTable.Fills, _check_surjective_table, _generate_surjective_table_dumb, _generate_surjective_table_pseudo
import numpy as np

num = 6
print(bells(num))
fills, table = FillTable._initialize_fill_table(num)
print(fills.shape)
print(table.shape)
#print(fills[fills.max(axis=1)==2])
print(fills)

In [ ]:
_generate_surjective_table_dumb(num, fills)

In [ ]:
_generate_surjective_table_pseudo(num, fills)

In [ ]:
_check_surjective_table(num, fills)

In [ ]:
%load_ext line_profiler
from Forms import *
from VampireUtils import *

def func():
    test_forms = FormTable(12, CLASSICAL_TRUTH, [CLASSICAL_IMPLICATION, CLASSICAL_NEGATION]) #14
    test_models = ModelTable(CN_SPEC, CN_STANDARD_MODEL) #[CLASSICAL_TRUTH, CLASSICAL_IMPLICATION, CLASSICAL_NEGATION]
    #test_models = ModelTable(Model([np.array([True, False, True], dtype=np.bool_), 
    #                                np.array([[1, 2, 0], [2, 2, 0], [1, 0, 1]], dtype=np.int8),
    #                                np.array([1, 2, 1], dtype=np.int8)])) #random 3 size
    
    #for forms, fills in test_forms.array:
    #    print(forms)

    test_forms.process(test_models, BLANK_VAMPIRE_WRAPPER, "test_excess.txt")

#%lprun -m ModelTools func()
%lprun -m Forms func()

In [ ]:
#11: 4s
#12: 13s
#13: 39s
#14: 118s

In [ ]:
list(range(1, 10))[1::2]

In [ ]:
def remove_duplicates(lst):
    seen = set()
    return [x for x in lst if x not in seen and not seen.add(x)]

# Example usage
lst = [1, 2, 2, 6, 3, 4, 1, 5, 3]
result = remove_duplicates(lst)
print(result)  # Output: [1, 2, 3, 4, 5]

In [ ]:
import numpy as np

arr = np.arange(8).reshape(2,2,2)
diagonal_dims = [2, 1, 0]
#print(arr.diagonal(0, diagonal_dims[0], diagonal_dims[1]))
#for indices in np.ndindex(arr.shape):
#    if indices[diagonal_dims[0]]==indices[diagonal_dims[1]]:
#        print(arr[indices])

grids = np.stack(np.meshgrid(*[np.arange(dim) for dim in arr.shape], indexing='ij'))
mask = np.all(grids[diagonal_dims[0]]==grids[diagonal_dims], axis=0)
print(arr[mask])
mask

In [ ]:
import numpy as np
from ModelTools import apply_fill_to_cache, _apply_fill_to_cache_forced_iteration

A = np.arange(81).reshape(3,3,3,3)
print(apply_fill_to_cache(A, np.array([5,5,5,2,3,3])))
print(_apply_fill_to_cache_forced_iteration(A, np.array([5,5,5,2,3,3])))
print(A)

In [ ]:
import numpy as np
def func(x):
    x += 1

A = np.array([0, 1, 2])
func(A[1:])
A

In [ ]:
def valid_dyck_word(word, arity = 2):
    if word[0]!=0:
        return False
    
    for i in range(1, len(word)):
        if word[i] > i * (arity - 1):
            return False
        if word[i] < word[i-1]:
            return False
        
    if word[-1]!=(len(word)-1)*(arity - 1):
        return False
        
    return True

def _iterate_word(word, arity = 2):
    word[-1] += 1
    i = len(word) - 1
    while word[i] > (i + 1) * (arity - 1):
        if i==0:
            word[0] = 10 * arity
            return
        word[i-1] += 1
        word[i] = word[i-1]
    
def word_iter(count, arity = 2):
    current_word = [0] * (count-1)
    while valid_dyck_word([0]+current_word+[count * (arity - 1)], arity=arity):
        yield [0]+current_word+[count * (arity - 1)]
        _iterate_word(current_word, arity=arity)

def dyck_word_to_exp(word, letter="D"):
    exp = ""
    for i in range(1, len(word)):
        exp += letter + "_" * (word[i] - word[i-1])
    exp += "_"
    return exp

word = [0,1,1,3,4]
print(valid_dyck_word(word))
print(dyck_word_to_exp(word))

word = [0,1,2,5,8]
print(valid_dyck_word(word, arity=3))
print(dyck_word_to_exp(word))
word = [1,2,6]
_iterate_word(word, arity=3)
print(word)

In [ ]:
for word in word_iter(3, arity=3):
    print(dyck_word_to_exp(word))

In [ ]:



CN = Form([('C', 2, 4), ('N', 1, 2)])
print("================")
print(CN.ground_state)
print("================")
print(CN._valid_state("C_CC_C__NN_"))
print("================")
print(CN._valid_state("CCCC_____NN"))
print("================")
print(CN._valid_state("CCC____C___"))
print("================")
print(CN._ground_state("C_CC_CNN___", level=2))

In [ ]:
CND = Form([('C', 2, 2), ('N', 1, 1), ('D', 3, 2)])
CND.check_iter()
for exp in CND:
    print(exp)

In [ ]:
CN.check_iter()

In [ ]:
for exp in CN:
    print(exp)

In [ ]:
'CCC_NC__N__'

In [ ]:
A = [0, 1, 2, 3]
A[2]

In [ ]:
ses = [set([1,2,3]), set([4,5,6]), set([2,4,6])]
list(set(itertools.chain.from_iterable(ses)))

In [ ]:
from FillTools import Fill


L5 = Fill(5)
for x in L5:
    print(x)
L5.check_iter()

In [ ]:
ord('a')-ord('b')

In [ ]:
from ModelTools import Model

expression = "TCCabNa"
a_mod = Model(operation_tables={"T": np.array([True, False]), "C": np.array([[0, 0], [0, 1]]), "N": np.array([1, 0])}, size=2)
print(a_mod.compile_expression(expression))
#a_mod.check_tautological(expression, "Unlikely")
a_mod.__call__(expression, "Verify")

In [ ]:
import numpy as np

A = np.random.rand(1, 1, 3, 1)
B = np.random.rand(1, 4, 1, 1)
(A * B).shape
C = np.random.rand(5, 2)
def idxC(*args):
    return C[*args]
idxC(np.array([2, 3]), np.array([[0], [1]]))
np.take(A, [0], axis=1).shape

In [ ]:
[0, 1, 2, 3][1:-1]

In [ ]:
hasattr([], "__len__")